name: toolhunt-api

services:
  fastapi-web:
    container_name: fastapi-web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=mysql://user:mypassword@db:3306/web_dev?charset=utf8mb4
      - DATABASE_TEST_URL=mysql://user:mypassword@db:3306/web_test?charset=utf8mb4
      - TOOLHUB_API_ENDPOINT=https://toolhub-demo.wmcloud.org/api/tools/
      - PYTHONPATH=/app
    command: uvicorn toolhunt.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mariadb
    image: mariadb:10.4
    restart: always
    environment:
      - MARIADB_USER=user
      - MARIADB_PASSWORD=mypassword
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=web_dev
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      interval: 10s
      retries: 10
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 90s

networks:
  toolhunt-net:
    name: toolhunt-net
    driver: bridge

volumes:
  dbdata:
