name: toolhunt-api

services:
  fastapi-web:
    container_name: fastapi-web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=mysql://user:mypassword@db:3306/mydatabase?charset=utf8mb4
    command: uvicorn toolhunt.main:app --reload --workers 1 --host 0.0.0.0 --port 8000

  db:
    container_name: mariadb
    image: mariadb:10.4
    restart: always
    environment:
      - MARIADB_USER=user
      - MARIADB_PASSWORD=mypassword
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=mydatabase
    volumes:
      - dbdata:/var/lib/mariadb/data/
    ports:
      - 3306

volumes:
  dbdata: